spring.application.name=Laboratory
spring.datasource.url=jdbc:mysql://localhost:3306/sys?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=19623333my
pcoi.upload.base-dir=D:/software_engin/PCOI/uploads/
pcoi.upload.url-prefix=/files/

